### ISSUE TITLE
nazwa pliku

### ISSUE THREAD

**Issue by 84lukaszkaminski** [palkak/palkak#1]
https://github.com/palkak/palkak/blob/77b528614c8be451b83f18c4b99a4f7e7c7adba0/index.html#L6

główny plik ze stylami zwykło się nazywać style.css

**Comment by palkak** [comment]
Poprawione, konfiguracja samego kompilowania była celem nadrzędnym, stad niedociągnięcia.

Dodatkowo: Pages włączone, do README dodałem link do strony 'homework'.
