### ISSUE TITLE
nagłówek w liście

### ISSUE THREAD

**Issue by 84lukaszkaminski** [palkak/palkak#4]
https://github.com/palkak/palkak/blob/77b528614c8be451b83f18c4b99a4f7e7c7adba0/index.html#L88

bezpośrednio w liście możemy zagnieżdżać tylko elementy listy lub inną listę. przeglądarka to łyknęła, ale umieszczanie h5 w liście to błąd

**Comment by palkak** [comment]
Poprawione.
